version: "3.9"
services:
  backend-php:
    build: ./backend
    container_name: backend-php
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/var/www/html
    networks: [appnet]

  backend-nginx:
    image: nginx:1.27-alpine
    container_name: backend-nginx
    depends_on: [backend-php]
    volumes:
      - ./backend:/var/www/html
      - ./backend/docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8081:80"
    networks: [appnet]

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on: [backend-nginx]
    ports:
      - "8080:80"
    networks: [appnet]

networks:
  appnet:
